# Generated by Django 3.1.2 on 2020-11-11 22:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_golive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoLive',
            new_name='Live',
        ),
    ]
